---
# playbook.yml
- name: 'Jiangren Packer demo2'
  hosts: default
  become: yes
  become_user: root
  user: ubuntu

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
